version: '3.4'
services:
    webapp:
        image: mcr.microsoft.com/vscode/devcontainers/go:1.23
        volumes:
            - ..:/home/vscode/workspaces/${localWorkspaceFolderBasename}:cached
        tty: true
        init: true
        command: sleep infinity
        ports:
        - "3000:3000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - ../data/db:/var/lib/mysql